version: '3.7'

services:
  mysql:
    image: mysql:innovation
    container_name: myslq_cont
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'America/Bogota'
    expose:
      - "3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network
  
  node:
    image: node:slim
    container_name: node_cont
    restart: always
    environment:
      TZ: 'America/Bogota'
    expose:
      - "9060"
    ports:
      - "9011:9060"
    networks:
      - my_network
    volumes:
      - ./:/home/node/app
    command: bash -c 'cd /home/node/app && npm start'

networks:
  my_network:
    driver: bridge